sudo: required

language: python

services:
  - docker

install:
  - pip install awscli

script:
  - docker --version
  - docker build -t methyldackel .

after_success:
  - docker images

before_deploy:
  - eval $(aws ecr get-login --no-include-email --region us-east-1) # AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
  - docker tag methyldackel:latest 002226384833.dkr.ecr.us-east-1.amazonaws.com/methyldackel:latest

deploy:
  provider: script
  script: docker push 002226384833.dkr.ecr.us-east-1.amazonaws.com/methyldackel:latest
  on:
    branch: master
