# Set following Environment Variables in Travis (* sensitive information):
# AWS_ACCESS_KEY_ID*:      IAM user that can push to ECR.
# AWS_SECRET_ACCESS_KEY*:  See above.
# DX_PROJECT:              ID of the dx project for official releases.
# DX_SANDBOX:              ID of the dx project for testing sandbox.
# DX_TOKEN*:               Token of the dx user that have Contribute access to
#                          DX_PROJECT and DX_SANDBOX.
sudo: required

dist: xenial

language: python

services:
  - docker

env:
  global:
    - ECR=002226384833.dkr.ecr.us-east-1.amazonaws.com
    - IMAGE=methyldackel  # configurable, must match the applet name defined in dxapp.json

install:
  - pip install awscli dxpy

before_script:
  - VERSION_CONTAINER="$(awk '$2 == "VERSION" { print $3; exit }' Dockerfile)"
  - eval $(aws ecr get-login --no-include-email --region us-east-1)
  - docker pull $ECR/$IMAGE:$VERSION_CONTAINER || true  # could fail if image isn't there
  - dx login --token $DX_TOKEN --noprojects --save
  - dx select $DX_SANDBOX

script:
  - echo "run test suite if there is any"
  - docker build --pull --cache-from $ECR/$IMAGE:$VERSION_CONTAINER -t $IMAGE .
  - docker run --rm $IMAGE
  - dx build dnanexus/$IMAGE --dry-run

after_success:
  - docker tag $IMAGE:latest $ECR/$IMAGE:$VERSION_CONTAINER
  - docker tag $IMAGE:latest $ECR/$IMAGE:latest
  - docker images

deploy:
  - provider: script
    script: bash scripts/deploy_dnanexus.sh
    on:
      branch: master
  - provider: script
    script: docker push $ECR/$IMAGE:$VERSION_CONTAINER && docker push $ECR/$IMAGE:latest
    on:
      tags: true
  - provider: script
    script: bash scripts/deploy_dnanexus.sh
    on:
      tags: true

