sudo: required

dist: xenial

language: python

services:
  - docker

env:
  global:
    - ECR=002226384833.dkr.ecr.us-east-1.amazonaws.com
    - IMAGE=methyldackel  # configurable, also need to be the same as the applet name defined in dxapp.json

install:
  - pip install dxpy

before_script:
  - dx login --token $DX_TOKEN --noprojects --save
  - dx select $DX_PROJECT

script:
  - echo "run test suite if there is any"
  - docker build -t $IMAGE .
  - docker run --rm $IMAGE
  - dx build dnanexus/$IMAGE --overwrite --dry-run

after_success:
  - docker images

# Can't configure before/after/deploy sections per provider
deploy:
  - provider: script
    script: bash scripts/deploy_docker.sh
    on:
      branch: master
  - provider: script
    script: bash scripts/deploy_dnanexus.sh
    on:
      tags: true

