sudo: required

language: python

services:
  - docker

install:
  - echo "install nothing!"

script:
  - echo "no tests!"

after_success:
  - docker --version
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --region us-east-1) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
  - docker build -t methyldackel .
  - docker tag methyldackel:latest 002226384833.dkr.ecr.us-east-1.amazonaws.com/methyldackel:latest
  - docker push 002226384833.dkr.ecr.us-east-1.amazonaws.com/methyldackel:latest
