# Set following Environment Variables in Travis (* sensitive information):
# AWS_ACCESS_KEY_ID*:      IAM user that can push to ECR.
# AWS_SECRET_ACCESS_KEY*:  See above.
# DX_PROJECT:              ID of the dx project for official releases.
# DX_SANDBOX:              ID of the dx project for testing sandbox.
# DX_TOKEN*:               Token of the dx user that have Contribute access to
#                          DX_PROJECT and DX_SANDBOX.
sudo: required

dist: xenial

language: python

services:
  - docker

branches:
  only:
  - master
  - /^ci-.*$/

env:
  global:
    - ECR=002226384833.dkr.ecr.us-east-1.amazonaws.com
    - IMAGE=methyldackel  # configurable, must match the applet name defined in dxapp.json

install:
  - pip install dxpy

before_script:
  - dx login --token $DX_TOKEN --noprojects --save
  - dx select $DX_SANDBOX

script:
  - echo "run test suite if there is any"   # run local test suite
  - docker build -t $IMAGE .                # build docker image
  - docker run --rm $IMAGE                  # test docker image
  - dx build dnanexus/$IMAGE --dry-run      # perform local checks

after_success:
  - VERSION_CONTAINER="$(awk '$2 == "VERSION" { print $3; exit }' Dockerfile)"
  - docker tag $IMAGE:latest $ECR/$IMAGE:$VERSION_CONTAINER
  - docker tag $IMAGE:latest $ECR/$IMAGE:latest
  - docker images

deploy:
  - provider: script
    script: bash scripts/deploy_dnanexus.sh
    on:
      branch: master
  - provider: script
    script: bash scripts/deploy_docker.sh
    on:
      tags: true
  - provider: script
    script: bash scripts/deploy_dnanexus.sh
    on:
      tags: true

